// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  EthereumCall,
  EthereumEvent,
  SmartContract,
  EthereumValue,
  JSONValue,
  TypedMap,
  Entity,
  EthereumTuple,
  Bytes,
  Address,
  BigInt,
  CallResult
} from "@graphprotocol/graph-ts";

export class NewAcoToken extends EthereumEvent {
  get params(): NewAcoToken__Params {
    return new NewAcoToken__Params(this);
  }
}

export class NewAcoToken__Params {
  _event: NewAcoToken;

  constructor(event: NewAcoToken) {
    this._event = event;
  }

  get underlying(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get strikeAsset(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get isCall(): boolean {
    return this._event.parameters[2].value.toBoolean();
  }

  get strikePrice(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get expiryTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get acoToken(): Address {
    return this._event.parameters[5].value.toAddress();
  }

  get acoTokenImplementation(): Address {
    return this._event.parameters[6].value.toAddress();
  }
}

export class ACOFactory extends SmartContract {
  static bind(address: Address): ACOFactory {
    return new ACOFactory("ACOFactory", address);
  }
}
