// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  EthereumCall,
  EthereumEvent,
  SmartContract,
  EthereumValue,
  JSONValue,
  TypedMap,
  Entity,
  EthereumTuple,
  Bytes,
  Address,
  BigInt,
  CallResult
} from "@graphprotocol/graph-ts";

export class NewAcoPool extends EthereumEvent {
  get params(): NewAcoPool__Params {
    return new NewAcoPool__Params(this);
  }
}

export class NewAcoPool__Params {
  _event: NewAcoPool;

  constructor(event: NewAcoPool) {
    this._event = event;
  }

  get underlying(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get strikeAsset(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get isCall(): boolean {
    return this._event.parameters[2].value.toBoolean();
  }

  get acoPool(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get acoPoolImplementation(): Address {
    return this._event.parameters[4].value.toAddress();
  }
}

export class ACOPoolFactory extends SmartContract {
  static bind(address: Address): ACOPoolFactory {
    return new ACOPoolFactory("ACOPoolFactory", address);
  }
}
